### ISSUE TITLE
iOS 13 and below throwing a syntax error

### ISSUE THREAD

**Issue by tedw** [cloudfour/image-compare#15]
Hey there, just wanted to share an iOS bug I ran into recently. In iOS 13 and below the following line causes a syntax error:

https://github.com/cloudfour/image-compare/blob/522e7369aa33540e89c3ca29ef06c6d396a58948/src/index.js#L169

```
SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
```

I removed this line from my [fork](https://github.com/Threespot/image-compare) and everything seems to work fine.

BTW thanks for making this plugin! I really appreciate the simplicity, and the fact that it’s accessible 🙌

**Comment by Paul-Hebert** [comment]
Great catch, thanks @tedw ! 

I'm glad you're liking the library. Your fork has some nice improvements! Let me know if you'd be interested in merging some of those back into this repo! (If you made a PR I'd be happy to review/approve/merge)
