### ISSUE TITLE
Allow to display a custom caption on each image

### ISSUE THREAD

**Issue by mably** [cloudfour/image-compare#71]
Everything is in the title.

**Comment by Paul-Hebert** [comment]
Hey @mably,

This is an interesting idea!

Could you attach a quick sketch or mockup of how the captions should be placed? It doesn't have to be fancy, but it would be helpful to get a sense of:

1. Where should each caption be placed?
2. How should the captions interact with the comparison slider? Are they both always visible? Or do they get obscured/clipped like the images?

(This may already be possible by passing in captions with your images in the `image-1` and `image-2` slots, but it depends on how you want this feature to work.)

**Comment by Paul-Hebert** [comment]
Odd! If you have a link or a reproduction I'd be happy to take a look.

**Comment by mably** [comment]
Talked too fast, the captions are displaying fine :)

But still some strange vertical distortion artefacts:

<img width="626" alt="image" src="https://github.com/cloudfour/image-compare/assets/385653/c26060e4-c23d-4357-a236-104351ad273e">

**Comment by Paul-Hebert** [comment]
Strange! Can you tell if any other CSS is impacting the figure display? It's hard to tell what's going on without a link to inspect.

**Comment by mably** [comment]
Here is an URL where you can see that when we are using `<figure>` there is some aspect ratio problem with the slider:

https://standardbm.e-bordeaux.org/image-compare-slider

<img width="480" alt="image" src="https://github.com/cloudfour/image-compare/assets/385653/adde47ee-8289-4f89-bad1-85123d258105">

- First slider without `figure`: OK
- Second slider with `figure`: KO

**Comment by Paul-Hebert** [comment]
@mably thanks for the link!

It looks like the issue is that the images aren't filling the container width. I tried adding the following CSS and it seemed to fix it:

```css
:where([slot='image-1'], [slot='image-2']) img {
  width: 100%;
}
```

Also, it looks like your `figure` elements have some margins applied. You may also want to add something like this:

```css
figure:where([slot='image-1'], [slot='image-2']) {
  margin: 0;
}
```

Hopefully that helps!

**Comment by mably** [comment]
@Paul-Hebert thanks for the tips, it works perfectly now 😀

<img width="577" alt="image" src="https://github.com/cloudfour/image-compare/assets/385653/268738bf-b017-4836-ae36-8f05f0c84184">

**Comment by Paul-Hebert** [comment]
Yay!
